# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://steventang2013.github.io
title: ST PERSONAL WEB
email: steven.tang@colorado.edu
description: > # "steventang2013.github.io is a personal website created for developmental purposes."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/steventang2013
  - title: linkedin
    url: https://www.linkedin.com/pub/steven-tang/a0/337/573

social_Extras:
  - title: star
    url: http://ghbtns.com/github-btn.html?user=twbs&amp;repo=bootstrap&amp;type=watch&amp;
    
